version: '3.7'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - pgfnnet
    ports:
      - 5432:5432

  minio:
    image: minio/minio:RELEASE.2023-01-31T02-24-19Z
    container_name: minio
    restart: unless-stopped
    networks:
      - pgfnnet
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - pgfnnet
    ports:
      - 8080:80

volumes:
  postgres-data:
  minio-data: 

# pgfnnet
networks:
  pgfnnet: